const data_dinner = [
    // --- SAFE ASSEMBLIES (FRIENDLY) ---
    {n:"Roast Chicken & Mashed Potatoes", s:"Friendly", c:"Dinner", d:"The 'Gold Standard' safe dinner. Use butter/salt, no lemon or onion."},
    {n:"Grilled Steak (Filet/Sirloin)", s:"Friendly", c:"Dinner", d:"Fresh beef is very safe. Request salt/butter only. No black pepper."},
    {n:"Baked Salmon & White Rice", s:"Friendly", c:"Dinner", d:"Omega-3s help inflammation. Bake with butter/dill (No lemon)."},
    {n:"Fettuccine Alfredo (Homemade)", s:"Friendly", c:"Dinner", d:"Cream and Parmesan are non-acidic. Do NOT add red pepper flakes."},
    {n:"Pork Tenderloin & Roasted Carrots", s:"Friendly", c:"Dinner", d:"Roast with rosemary and garlic. Very low acid and safe."},
    {n:"Baked Potato (Loaded Safe)", s:"Friendly", c:"Dinner", d:"Use butter, sour cream, and chives. Avoid bacon bits with nitrates."},
    {n:"White Pizza (Garlic & Oil)", s:"Friendly", c:"Dinner", d:"Mozzarella and garlic/oil base. No tomato sauce or pepperoni."},
    {n:"Chicken & Rice Stir Fry (Plain)", s:"Friendly", c:"Dinner", d:"Use salt/oil/garlic only. Avoid soy sauce and ginger."},
    {n:"Beef Stew (Homemade/Bland)", s:"Friendly", c:"Dinner", d:"Broth, potatoes, carrots, beef. No wine, tomato, or onions."},
    {n:"Baked Cod / Halibut", s:"Friendly", c:"Dinner", d:"Bland white fish is very safe. Use butter and herbs."},
    {n:"Shrimp Scampi (No Wine/Lemon)", s:"Friendly", c:"Dinner", d:"Sauté shrimp in butter and fresh garlic over white pasta."},
    {n:"Ground Beef Patty (Plain)", s:"Friendly", c:"Dinner", d:"Fresh beef is safe. Skip the bun if it has preservatives/seeds."},
    {n:"Turkey Pot Pie (Homemade)", s:"Friendly", c:"Dinner", d:"Safe if crust is basic and gravy is just flour/broth (no onion)."},
    {n:"Pasta with Garlic & Olive Oil", s:"Friendly", c:"Dinner", d:"Simple and non-irritating. Add chicken for protein."},
    {n:"Lamb Chops & Peas", s:"Friendly", c:"Dinner", d:"Naturally safe and nutrient dense. Keep seasoning simple."},
    {n:"Rotisserie Chicken (White Meat)", s:"Friendly", c:"Dinner", d:"Remove skin (spices/acid). Inner meat is a safe baseline."},
    {n:"Chicken Risotto (Mushroom)", s:"Friendly", c:"Dinner", d:"Safe and creamy. Avoid adding wine or heavy pepper."},
    {n:"Beef Roast w/ Potatoes", s:"Friendly", c:"Dinner", d:"Slow cooked baseline. Use salt, avoid onion powder."},
    {n:"Scallops (Pan Seared)", s:"Friendly", c:"Dinner", d:"Safe and non-acidic. Sauté in butter."},
    {n:"Egg & Rice Bowl", s:"Friendly", c:"Dinner", d:"Comforting and safe. Scrambled eggs over jasmine rice."},
    {n:"Turkey Burger (Plain)", s:"Friendly", c:"Dinner", d:"Safe if meat is fresh. No ketchup/mustard."},
    {n:"Chicken & Dumplings", s:"Friendly", c:"Dinner", d:"Safe if homemade without onions or processed bouillon."},
    {n:"Baked Ham (Uncured)", s:"Friendly", c:"Dinner", d:"Safe if nitrate-free. Avoid honey/clove glazes if sensitive."},
    {n:"Lobster Tail (Butter only)", s:"Friendly", c:"Dinner", d:"Luxury safe choice. No lemon or cocktail sauce."},
    {n:"Zucchini Noodles (Alfredo)", s:"Friendly", c:"Dinner", d:"Low-acid vegetable base with safe cream sauce."},
    {n:"Roast Duck (Plain)", s:"Friendly", c:"Dinner", d:"Safe. Avoid fruit-based glazes like orange or cherry."},
    {n:"Beef Tips & Noodles", s:"Friendly", c:"Dinner", d:"Safe and filling. Use butter and salt."},
    {n:"Chicken Cutlets (Breaded/Plain)", s:"Friendly", c:"Dinner", d:"Safe if fried in clean oil. No lemon squeeze."},
    {n:"Shepherd's Pie (Bland)", s:"Friendly", c:"Dinner", d:"Ground beef/lamb, potatoes, peas. No onion/tomato paste."},
    {n:"Quinoa & Roasted Veg Bowl", s:"Friendly", c:"Dinner", d:"High protein and non-acidic. Use olive oil."},
    {n:"Tilapia w/ Butter & Herbs", s:"Friendly", c:"Dinner", d:"Very safe white fish baseline."},
    {n:"Beef Kabobs (Squash/Mushrooms)", s:"Friendly", c:"Dinner", d:"Safe if grilled without vinegar-based marinades."},
    {n:"Chicken Breast w/ Honey Glaze", s:"Friendly", c:"Dinner", d:"Safe sweet flavor. Avoid citrus-based glazes."},

    // --- CAUTION DINNER ---
    {n:"Chicken Burrito (No Salsa)", s:"Caution", c:"Dinner", d:"Rice and chicken only. Avoid beans and onions."},
    {n:"Sushi (California Roll)", s:"Caution", c:"Dinner", d:"Imitation crab can have dyes/sugar. No soy sauce."},
    {n:"Philly Cheesesteak (No Onions)", s:"Caution", c:"Dinner", d:"Beef and cheese are safe, but bread/oil can be a trigger."},
    {n:"Fish Tacos (Flour Tortilla)", s:"Caution", c:"Dinner", d:"Use grilled fish, no lime, no salsa. Use sour cream."},
    {n:"Lasagna (White Sauce)", s:"Caution", c:"Dinner", d:"Cheese and cream are safe, but check for hidden spices."},
    {n:"Baked Beans", s:"Caution", c:"Dinner", d:"High sugar and spices. Can be an inflammatory trigger."},
    {n:"Fried Chicken (Plain)", s:"Caution", c:"Dinner", d:"Check for 'spicy' breading or MSG in the oil."},

    // --- AVOID DINNER (TRIGGERS) ---
    {n:"Spaghetti Marinara", s:"Avoid", c:"Dinner", d:"Pure acid. Guaranteed 'lemon on a cut' feeling."},
    {n:"Pizza (Red Sauce/Pepperoni)", s:"Avoid", c:"Dinner", d:"Massive trigger. Acid + Spicy meat = 200ml emergency."},
    {n:"Chili (Beef or Bean)", s:"Avoid", c:"Dinner", d:"Onion, spice, and tomato 'triple threat'."},
    {n:"Tacos / Enchiladas", s:"Avoid", c:"Dinner", d:"Onion, lime, and chili powder will burn the urethra."},
    {n:"BBQ Ribs / Chicken", s:"Avoid", c:"Dinner", d:"BBQ sauce is vinegar and sugar based. High flare risk."},
    {n:"Lasagna (Red Sauce)", s:"Avoid", c:"Dinner", d:"Tomato, spicy sausage, and onions. Avoid entirely."},
    {n:"Curry (Thai/Indian)", s:"Avoid", c:"Dinner", d:"Hidden hot spices and acids. High risk for prostate burning."},
    {n:"Buffalo Chicken Wings", s:"Avoid", c:"Dinner", d:"Vinegar-based hot sauce is the worst trigger."},
    {n:"Cajun Seafood Boil", s:"Avoid", c:"Dinner", d:"Spices and lemon will cause immediate sharp pain."},
    {n:"Chinese (Orange Chicken)", s:"Avoid", c:"Dinner", d:"Citrus and heavy soy sauce. Major flare trigger."},
    {n:"Sloppy Joes", s:"Avoid", c:"Dinner", d:"Tomato paste, onion, and sugar. High-level irritant."},
    {n:"Meatloaf (Store Bought)", s:"Avoid", c:"Dinner", d:"Usually contains heavy onion powder and ketchup."},
    {n:"Pot Roast (Wine Based)", s:"Avoid", c:"Dinner", d:"Alcohol and acid from wine sting the bladder lining."},
    {n:"Shrimp Scampi (Lemon/Wine)", s:"Avoid", c:"Dinner", d:"Standard restaurant version is highly acidic."},
    {n:"Pasta Puttanesca", s:"Avoid", c:"Dinner", d:"Olives, capers, and tomato are all pure acid."},
    {n:"Beef Stir Fry (Soy Sauce)", s:"Avoid", c:"Dinner", d:"Soy sauce and ginger are common nerve irritants."}
];
