const data_lunch = [
    // --- SAFE ASSEMBLIES (FRIENDLY) ---
    {n:"Turkey & Mozzarella Wrap", s:"Friendly", c:"Lunch", d:"Applegate turkey, mild mozzarella, flour tortilla. No mustard/mayo."},
    {n:"Peanut Butter & Honey Sandwich", s:"Friendly", c:"Lunch", d:"Safe staple. Honey is non-acidic and soothing."},
    {n:"Chicken Salad (Olive Oil)", s:"Friendly", c:"Lunch", d:"Safe if using olive oil/herbs. No mayo or lemon."},
    {n:"Cottage Cheese & Pears", s:"Friendly", c:"Lunch", d:"High protein and very soothing for the bladder lining."},
    {n:"Hard Boiled Eggs & Pretzels", s:"Friendly", c:"Lunch", d:"Low-irritant 'power pack'. Extremely safe."},
    {n:"Roast Beef Sandwich (Plain)", s:"Friendly", c:"Lunch", d:"Fresh roast beef on white bread. No horseradish."},
    {n:"Jasmine Rice Bowl (Chicken & Zucchini)", s:"Friendly", c:"Lunch", d:"Steamed baseline. Use salt and butter for flavor."},
    {n:"Egg Salad (Plain)", s:"Friendly", c:"Lunch", d:"Use butter/oil for moisture. Skip the mustard/mayo."},
    {n:"Thermos Beef Stew (Homemade)", s:"Friendly", c:"Lunch", d:"Broth, potatoes, carrots. No wine or onions."},
    {n:"Hummus & Pita", s:"Friendly", c:"Lunch", d:"Safe Mediterranean option. Watch for heavy garlic/lemon."},
    {n:"Quesadilla (Plain Cheese)", s:"Friendly", c:"Lunch", d:"Safe. Dip in sour cream, not salsa."},
    {n:"Leftover Roast Chicken", s:"Friendly", c:"Lunch", d:"Remove skin if it has spicy rubs. Very safe."},
    {n:"Subway Turkey (Plain)", s:"Friendly", c:"Lunch", d:"White bread, no onions/peppers. Use oil/salt/oregano."},
    {n:"Chick-Fil-A Grilled Nuggets", s:"Friendly", c:"Lunch", d:"Safe fast food choice. Avoid dipping sauces."},
    {n:"Pasta Salad (Oil Based)", s:"Friendly", c:"Lunch", d:"Oil and herbs only. No vinegar or lemon."},
    {n:"Bagel with Cream Cheese", s:"Friendly", c:"Lunch", d:"Plain/Blueberry bagel only. No 'Everything' toppings."},
    {n:"Rice Cakes & Almond Butter", s:"Friendly", c:"Lunch", d:"Crunchy and safe. High protein, low acid."},
    {n:"Baked Potato (Butter/Chives)", s:"Friendly", c:"Lunch", d:"Safe and filling. Chives are generally safe."},
    {n:"Pancakes (Plain)", s:"Friendly", c:"Lunch", d:"Breakfast for lunch. Use pure maple syrup."},
    {n:"Salmon Salad (Oil Based)", s:"Friendly", c:"Lunch", d:"Flaked salmon with herbs/oil. No lemon."},
    {n:"Turkey & Provolone Sandwich", s:"Friendly", c:"Lunch", d:"Provolone is mild and safe. Use white bread."},
    {n:"Cucumber & Cream Cheese Sandwich", s:"Friendly", c:"Lunch", d:"Cooling and hydrating for a burning bladder."},
    {n:"Beef Kabob (Plain)", s:"Friendly", c:"Lunch", d:"Grilled beef and squash. No spicy marinades."},
    {n:"Quinoa Salad (Herb/Oil)", s:"Friendly", c:"Lunch", d:"High protein grain. No vinaigrette."},
    {n:"Steamed Shrimp (Plain)", s:"Friendly", c:"Lunch", d:"Safe if not canned. No cocktail sauce."},
    {n:"Ricotta on Toast w/ Honey", s:"Friendly", c:"Lunch", d:"Soothing dairy-based lunch."},
    {n:"Beef Pot Roast Leftovers", s:"Friendly", c:"Lunch", d:"Safe if not cooked with wine or onion."},
    {n:"Fish Fillet (Breaded/Plain)", s:"Friendly", c:"Lunch", d:"Safe white fish. No tartar sauce."},
    {n:"Peanut Butter & Banana Wrap", s:"Friendly", c:"Lunch", d:"High energy and low acid. Safe."},
    {n:"Chicken Pita (No Onions)", s:"Friendly", c:"Lunch", d:"Grilled chicken, pita, lettuce. No dressing."},
    {n:"Grilled Cheese (White Bread)", s:"Friendly", c:"Lunch", d:"Use mild cheddar/mozzarella. No tomato soup."},
    {n:"Chicken Tenders (Plain)", s:"Friendly", c:"Lunch", d:"Safe if not spicy. Avoid dipping sauces."},
    {n:"Steamed Mussels (Butter)", s:"Friendly", c:"Lunch", d:"Safe if no wine/garlic/onion in broth."},
    {n:"Roast Beef & Swiss Wrap", s:"Friendly", c:"Lunch", d:"Swiss is mild. Use plain flour tortilla."},
    {n:"Lentil Soup (Homemade)", s:"Friendly", c:"Lunch", d:"Safe if no onions/tomatoes used in base."},
    {n:"Chicken & Wild Rice Soup", s:"Friendly", c:"Lunch", d:"Bland and safe. Avoid 'Cream of' versions."},
    {n:"White Pizza Leftovers", s:"Friendly", c:"Lunch", d:"Garlic/Oil base. No red sauce."},
    {n:"Cold Pasta (Oil/Herbs)", s:"Friendly", c:"Lunch", d:"Non-acidic and filling. Safe."},
    {n:"Cornbread & Honey", s:"Friendly", c:"Lunch", d:"Safe. Avoid jalapeño cornbread."},
    {n:"Shrimp & Grits (Plain)", s:"Friendly", c:"Lunch", d:"Safe southern lunch. No spicy gravy."},
    {n:"Bagel w/ Peanut Butter", s:"Friendly", c:"Lunch", d:"Plain bagel. Safe protein/fiber combo."},
    {n:"Fruit Salad (Pears/Melon)", s:"Friendly", c:"Lunch", d:"Avoid citrus/grapes in the mix."},
    {n:"Egg & Cheese Biscuit", s:"Friendly", c:"Lunch", d:"Safe breakfast-style lunch."},
    {n:"Roast Turkey Drumstick", s:"Friendly", c:"Lunch", d:"Very safe and high protein."},
    {n:"Baked Salmon (Cold)", s:"Friendly", c:"Lunch", d:"Great leftover lunch. No lemon."},
    {n:"Beef Tips on Rice", s:"Friendly", c:"Lunch", d:"Safe and savory. Use salt, no pepper."},
    {n:"French Dip (No Onions)", s:"Friendly", c:"Lunch", d:"Roast beef and au jus. Avoid horseradish."},
    {n:"Chicken Noodle (Homemade)", s:"Friendly", c:"Lunch", d:"Safe if using low-sodium broth, no onion."},
    {n:"Cheese and Crackers", s:"Friendly", c:"Lunch", d:"Mild cheeses only. No aged cheddar."},
    {n:"Roast Beef & Provolone", s:"Friendly", c:"Lunch", d:"Provolone is non-irritating."},
    {n:"Chicken Wrap (No Dressing)", s:"Friendly", c:"Lunch", d:"Safe on-the-go choice."},
    {n:"Yogurt w/ Granola & Pears", s:"Friendly", c:"Lunch", d:"Low-acid vanilla yogurt only."},
    {n:"English Muffin Pizza (White)", s:"Friendly", c:"Lunch", d:"Garlic/Oil base. Safe."},
    {n:"Boiled Shrimp & Rice", s:"Friendly", c:"Lunch", d:"Very safe and light lunch."},
    {n:"Pork Chop Leftovers", s:"Friendly", c:"Lunch", d:"Safe protein. No spicy rubs."},
    {n:"Turkey Slider (Plain)", s:"Friendly", c:"Lunch", d:"Safe. No condiments."},
    {n:"Cucumber Roll (Sushi)", s:"Friendly", c:"Lunch", d:"Safest sushi option. No soy."},
    {n:"Cashews & Dried Pears", s:"Friendly", c:"Lunch", d:"Safe high-energy snack lunch."},
    {n:"Cottage Cheese & Honey", s:"Friendly", c:"Lunch", d:"Very soothing dairy lunch."},
    {n:"Roast Chicken & Rice", s:"Friendly", c:"Lunch", d:"The ultimate safe baseline lunch."},

    // --- CAUTION LUNCH ---
    {n:"Ham & Swiss (Uncured)", s:"Caution", c:"Lunch", d:"Safe if nitrate-free. Swiss is generally low-irritant."},
    {n:"Chicken Caesar (No Dressing)", s:"Caution", c:"Lunch", d:"Dressing is acidic. Use olive oil and salt instead."},
    {n:"Tuna Pouch (Plain)", s:"Caution", c:"Lunch", d:"Check for 'vegetable broth' (hidden soy/onion)."},
    {n:"Falafel Wrap", s:"Caution", c:"Lunch", d:"Generally safe, but check for heavy garlic/onion."},
    {n:"Crab Cakes (Plain)", s:"Caution", c:"Lunch", d:"Check for mustard or lemon juice in the mix."},
    {n:"Chicken Burrito (No Salsa)", s:"Caution", c:"Lunch", d:"Meat and rice only. No beans/onion/salsa."},
    {n:"Cottage Cheese & Blueberries", s:"Caution", c:"Lunch", d:"Blueberries are safer than most, but test."},
    {n:"Egg & Bacon Biscuit", s:"Caution", c:"Lunch", d:"Nitrate-free bacon only."},
    {n:"Peanut Butter & Apples", s:"Caution", c:"Lunch", d:"Use Gala/Fuji apples only."},
    {n:"Ham & Cheese Sliders", s:"Caution", c:"Lunch", d:"Safe if meat is nitrate-free."},
    {n:"Chicken Tacos (Plain)", s:"Caution", c:"Lunch", d:"Flour tortilla, no salsa/onion. Use sour cream."},
    {n:"Turkey & Avocado Toast", s:"Caution", c:"Lunch", d:"Avocado is safe for some, trigger for others."},
    {n:"Turkey Club (Plain)", s:"Caution", c:"Lunch", d:"Remove tomato and onion. Nitrate-free bacon only."},

    // --- AVOID LUNCH (TRIGGERS) ---
    {n:"Everything Bagel", s:"Avoid", c:"Lunch", d:"Raw onion/garlic are major prostate irritants."},
    {n:"Italian Sub", s:"Avoid", c:"Lunch", d:"Spicy meats and vinegar are massive triggers."},
    {n:"Taco Bell Bean Burrito", s:"Avoid", c:"Lunch", d:"Onions and red sauce cause immediate burning."},
    {n:"Canned Chicken Noodle Soup", s:"Avoid", c:"Lunch", d:"High sodium and hidden onion/garlic powder."},
    {n:"Greek Salad", s:"Avoid", c:"Lunch", d:"Feta and vinaigrette are high-acid triggers."},
    {n:"Egg Salad (Mayo/Mustard)", s:"Avoid", c:"Lunch", d:"Mustard and mayo acids burn the lining."},
    {n:"Pepperoni Pizza", s:"Avoid", c:"Lunch", d:"Tomato sauce and spicy meat are huge triggers."},
    {n:"Chef Salad (Ham/Tomato)", s:"Avoid", c:"Lunch", d:"Dressing and tomato are pure acid."},
    {n:"Sushi (Spicy Tuna)", s:"Avoid", c:"Lunch", d:"Spicy mayo and chili are urethral irritants."},
    {n:"Chili (Beef or Bean)", s:"Avoid", c:"Lunch", d:"Onion, spice, and tomato 'triple threat'."},
    {n:"Cold Cuts (Standard)", s:"Avoid", c:"Lunch", d:"Nitrates and preservatives irritate veiny tissue."},
    {n:"Hot Dogs", s:"Avoid", c:"Lunch", d:"Nitrates and chemicals trigger frequency."},
    {n:"Chicken Wings (Buffalo)", s:"Avoid", c:"Lunch", d:"Vinegar-based hot sauce is the worst trigger."},
    {n:"Macaroni Salad (Store)", s:"Avoid", c:"Lunch", d:"Vinegar and mustard are major irritants."},
    {n:"Potato Salad (Mayo Based)", s:"Avoid", c:"Lunch", d:"Vinegar in the dressing triggers spasms."},
    {n:"Canned Ravioli", s:"Avoid", c:"Lunch", d:"Acidic tomato sauce and preservatives."},
    {n:"Veggie Burger (Soy Based)", s:"Avoid", c:"Lunch", d:"Soy is a top-tier bladder irritant."},
    {n:"Bologna Sandwich", s:"Avoid", c:"Lunch", d:"High nitrates and fillers sting the lining."},
    {n:"Frozen Entrees (Lean Cuisine)", s:"Avoid", c:"Lunch", d:"High sodium and preservatives."},
    {n:"Barbecue Chicken", s:"Avoid", c:"Lunch", d:"BBQ sauce is vinegar and sugar based."},
    {n:"Stuffed Peppers (Rice/Beef)", s:"Avoid", c:"Lunch", d:"Tomato sauce and peppers trigger pain."},
    {n:"Tuna Salad (Mayo Based)", s:"Avoid", c:"Lunch", d:"Mayo and lemon are major triggers."},
    {n:"Salami & Crackers", s:"Avoid", c:"Lunch", d:"Nitrates and spices burn the lining."},
    {n:"Pimento Cheese Sandwich", s:"Avoid", c:"Lunch", d:"Pimentos and preservatives trigger spasms."},
    {n:"Ham Salad Sandwich", s:"Avoid", c:"Lunch", d:"Nitrates and mustard/mayo base."}
];
