    // --- ADDITIONAL SAFE CRUNCH & SAVORY ---
    {n:"Rice Works Sea Salt Crisps", s:"Friendly", c:"Snacks", d:"Clean brown rice crisps. Safe alternative to tortilla chips."},
    {n:"Harvest Snaps (Lightly Salted)", s:"Friendly", c:"Snacks", d:"Pea crisps. Check for citric acid; original salted is usually safe."},
    {n:"Barnana Plantain Chips (Pink Salt)", s:"Friendly", c:"Snacks", d:"Safe starch. Ensure no lime juice on the ingredients."},
    {n:"Enjoy Life Lentil Chips (Plain)", s:"Friendly", c:"Snacks", d:"Top-tier allergy-friendly brand; no common irritants."},
    {n:"Milton’s Gluten Free Crackers", s:"Friendly", c:"Snacks", d:"Sea Salt version is very bland and bladder-friendly."},
    {n:"Simply Tostitos (Sea Salt)", s:"Friendly", c:"Snacks", d:"Organic corn and salt; safer than standard versions with 'natural flavors'."},
    {n:"Pirate’s Booty (Aged White Cheddar)", s:"Caution", c:"Snacks", d:"Lower acid than Cheetos, but some find the 'Aged' cheese triggers a minor itch."},
    {n:"Blue Diamond Nut-Thins (Original)", s:"Friendly", c:"Snacks", d:"Rice and nut cracker. Non-acidic and safe."},
    {n:"Mary’s Gone Crackers (Original)", s:"Friendly", c:"Snacks", d:"Safe seeds and grains. Avoid 'Black Pepper' version."},
    {n:"Lundberg Rice Cakes (Tamari-Free)", s:"Friendly", c:"Snacks", d:"Stick to Sea Salt or Brown Rice versions. Avoid Tamari (soy)."},
    {n:"Snyder’s Rods", s:"Friendly", c:"Snacks", d:"Thick pretzels are great for buffering stomach acid."},
    {n:"Way Better Snacks (Plain Corn)", s:"Friendly", c:"Snacks", d:"Sprouted grains; generally easier to digest and safe."},
    {n:"Wheat Thins (Original)", s:"Caution", c:"Snacks", d:"Generally safe, but high sugar content can be a minor inflammatory."},
    {n:"Simple Truth (Kroger) Veggie Straws", s:"Caution", c:"Snacks", d:"Check for citric acid. The plain sea salt version is usually safe."},

    // --- ADDITIONAL SWEET & DESSERT ---
    {n:"Magnum White Chocolate Bar", s:"Friendly", c:"Snacks", d:"Pure white chocolate coating is safe. Avoid versions with fruit swirls."},
    {n:"Häagen-Dazs Vanilla Bean", s:"Friendly", c:"Snacks", d:"Clean ingredients. Avoid 'Chocolate' or 'Coffee' flavors."},
    {n:"Breyers Natural Vanilla", s:"Friendly", c:"Snacks", d:"Very few additives. Safe baseline dessert."},
    {n:"Nilla Wafer Pudding (Vanilla)", s:"Friendly", c:"Snacks", d:"Safe comfort snack. Use real milk to help buffer pH."},
    {n:"Golden Oreos", s:"Caution", c:"Snacks", d:"No chocolate, but high in preservatives. Test small amounts."},
    {n:"Shortbread Fingers (Keebler)", s:"Friendly", c:"Snacks", d:"Simple fats and flour. Non-acidic."},
    {n:"Teddy Grahams (Honey)", s:"Friendly", c:"Snacks", d:"Safe for kids and adults. No chocolate or dyes."},
    {n:"Fig Newtons", s:"Caution", c:"Snacks", d:"Figs can be a trigger for some due to tyramine/acid. Test small."},
    {n:"Fortune Cookies (Bulk)", s:"Friendly", c:"Snacks", d:"Very safe; almost no flavor irritants."},
    {n:"Tapioca Pudding", s:"Friendly", c:"Snacks", d:"Very soothing for the gut and bladder. Use vanilla only."},
    {n:"Homemade Pear Crisp", s:"Friendly", c:"Snacks", d:"Oats, butter, sugar, and pears. The ultimate safe dessert."},

    // --- CANDY (NO ACID / NO DYES) ---
    {n:"Andes White Mints", s:"Friendly", c:"Snacks", d:"Safe alternative to chocolate mints. Peppermint is soothing."},
    {n:"Altoids (Peppermint)", s:"Friendly", c:"Snacks", d:"Strong, but safe. Avoid 'Cinnamon' or 'Fruit' flavors."},
    {n:"Mentos (Mint)", s:"Friendly", c:"Snacks", d:"Safe chewy mint. Avoid 'Fruit' Mentos entirely."},
    {n:"Necco Wafers (White/Wintergreen)", s:"Friendly", c:"Snacks", d:"Avoid the fruit-flavored wafers in the pack."},
    {n:"Rock Candy (Clear)", s:"Friendly", c:"Snacks", d:"Pure sugar. Safe as long as there is no dye or flavoring."},
    {n:"Salt Water Taffy (Vanilla/Vanilla Bean)", s:"Friendly", c:"Snacks", d:"Safe. Avoid 'Cherry,' 'Lemon,' or 'Orange' flavors."},

    // --- THE RED LIST (AVOID - HIDDEN ACID/CHEMICALS) ---
    {n:"Skittles (All types)", s:"Avoid", c:"Snacks", d:"Pure citric and malic acid. Guaranteed to trigger burning."},
    {n:"Gummy Bears (Haribo)", s:"Avoid", c:"Snacks", d:"Citric acid is the primary preservative. Major flare risk."},
    {n:"Sour Patch Kids", s:"Avoid", c:"Snacks", d:"Coated in malic acid 'dust'. Extremely aggressive on the bladder."},
    {n:"Starburst", s:"Avoid", c:"Snacks", d:"Fruit acid and Red 40. High risk for 200ml emergencies."},
    {n:"Pringles (Sour Cream / BBQ)", s:"Avoid", c:"Snacks", d:"High levels of MSG and citric acid. Major nerve irritant."},
    {n:"Doritos (Cool Ranch / Nacho)", s:"Avoid", c:"Snacks", d:"Dyes and MSG. Triggers 'burning itch' at the prostate."},
    {n:"Takis / Hot Chips", s:"Avoid", c:"Snacks", d:"Capsaicin and Red Dye 40. Extreme urethral irritant."},
    {n:"SunChips (Garden Salsa / French Onion)", s:"Avoid", c:"Snacks", d:"Onion powder and spices. Irritates the bladder neck."},
    {n:"Fruit Roll-ups / Fruit by the Foot", s:"Avoid", c:"Snacks", d:"Concentrated acid and chemical dyes. Massive trigger."},
    {n:"Raisins / Sun-Maid Packs", s:"Avoid", c:"Snacks", d:"Highly acidic when digested. Causes rapid burning."},
    {n:"Beef Sticks / Slim Jims", s:"Avoid", c:"Snacks", d:"Nitrates and preservatives. Bad for veiny bladder lining."},
    {n:"Chocolate Pretzels", s:"Avoid", c:"Snacks", d:"The chocolate caffeine overrides the 'safe' pretzel."},
    {n:"Snickers / Twix / Milky Way", s:"Avoid", c:"Snacks", d:"Caffeine and corn syrup fuel tissue inflammation."},
    {n:"Yogurt Covered Snacks (Store)", s:"Avoid", c:"Snacks", d:"Usually highly processed with lemon juice/acid."},
    {n:"Cranberry Trail Mix", s:"Avoid", c:"Snacks", d:"Craisins are pure acid for an IC bladder."},
    {n:"Instant Pudding (Chocolate)", s:"Avoid", c:"Snacks", d:"Caffeine and preservatives. Use Vanilla instead."},
    {n:"Licorice (Red/Cherry)", s:"Avoid", c:"Snacks", d:"Red Dye 40 and citric acid. High risk."},
    {n:"Vending Machine Donuts", s:"Avoid", c:"Snacks", d:"Preservatives and alcohol-based vanilla sting the lining."},
    {n:"Sugar-Free Mentos", s:"Avoid", c:"Snacks", d:"Artificial sweeteners are bladder neurotoxins."}
