const data_spices = [
    // --- OILS & FATS (THE PANTRY BASE) ---
    {n:"Olive Oil (Extra Virgin)", s:"Friendly", c:"Seasonings", d:"The safest cooking/dressing oil. Very anti-inflammatory."},
    {n:"Butter (Unsalted)", s:"Friendly", c:"Seasonings", d:"Safe baseline fat. Avoid margarines with many additives."},
    {n:"Coconut Oil (Refined/Unrefined)", s:"Friendly", c:"Seasonings", d:"Safe for high-heat cooking and baking."},
    {n:"Ghee (Clarified Butter)", s:"Friendly", c:"Seasonings", d:"Very safe; removes milk solids that can irritate some."},
    {n:"Canola Oil", s:"Friendly", c:"Seasonings", d:"Generally safe, non-acidic cooking oil."},
    {n:"Vegetable Oil", s:"Friendly", c:"Seasonings", d:"Safe baseline for frying or baking."},
    {n:"Lard / Animal Fats", s:"Friendly", c:"Seasonings", d:"Generally safe if plain. Avoid pre-seasoned 'Taco' fats."},
    {n:"Avocado Oil", s:"Caution", c:"Seasonings", d:"Generally safe, but avocado is a trigger for some patients."},
    {n:"Sesame Oil", s:"Caution", c:"Seasonings", d:"Usually safe in small amounts, but toasted versions can be sharp."},
    {n:"Peanut Oil", s:"Friendly", c:"Seasonings", d:"Safe for high-heat frying. Non-acidic."},

    // --- SWEETENERS ---
    {n:"Honey (Raw/Clover)", s:"Friendly", c:"Seasonings", d:"The safest natural sweetener. Anti-bacterial and soothing."},
    {n:"Maple Syrup (100% Pure)", s:"Friendly", c:"Seasonings", d:"Safe and non-acidic. Do not use 'Pancake Syrup' (High Fructose)."},
    {n:"Brown Sugar (Light/Dark)", s:"Caution", c:"Seasonings", d:"Safe in moderation. High sugar can fuel systemic inflammation."},
    {n:"White Sugar / Cane Sugar", s:"Caution", c:"Seasonings", d:"Generally safe, but avoid excessive amounts during a flare."},
    {n:"Molasses", s:"Friendly", c:"Seasonings", d:"Safe and nutrient-dense alternative sweetener."},
    {n:"Agave Nectar", s:"Caution", c:"Seasonings", d:"Low glycemic, but some find it irritating to the bladder lining."},
    {n:"Stevia (Pure)", s:"Caution", c:"Seasonings", d:"The only 'safe-ish' natural sweetener; test small amounts."},

    // --- HERBS (SAFE ZONE) ---
    {n:"Basil (Fresh/Dried)", s:"Friendly", c:"Seasonings", d:"Very safe. Great for flavoring pasta and chicken."},
    {n:"Oregano", s:"Friendly", c:"Seasonings", d:"Staple herb. Non-irritating for the bladder."},
    {n:"Parsley", s:"Friendly", c:"Seasonings", d:"Fresh and safe. Helps with digestion and won't sting."},
    {n:"Thyme", s:"Friendly", c:"Seasonings", d:"Excellent for roasting meats and flavoring stews safely."},
    {n:"Rosemary", s:"Friendly", c:"Seasonings", d:"Very safe and aromatic. Great with potatoes and pork."},
    {n:"Sage", s:"Friendly", c:"Seasonings", d:"Safe and savory. Excellent in butter sauces for pasta."},
    {n:"Dill", s:"Friendly", c:"Seasonings", d:"The 'Gold Standard' for fish and potatoes. Very soothing."},
    {n:"Chives (Fresh)", s:"Friendly", c:"Seasonings", d:"Safe. The best way to get 'onion' flavor without the prostate irritation."},
    {n:"Bay Leaves", s:"Friendly", c:"Seasonings", d:"Safe for flavoring soups. Remove before eating."},
    {n:"Cilantro / Coriander", s:"Friendly", c:"Seasonings", d:"Generally very safe; adds fresh flavor without acid."},
    {n:"Tarragon", s:"Friendly", c:"Seasonings", d:"Safe and mild. Good for chicken or egg dishes."},
    {n:"Marjoram", s:"Friendly", c:"Seasonings", d:"Sweet, mild herb similar to oregano but gentler."},
    {n:"Savory", s:"Friendly", c:"Seasonings", d:"Peppery flavor without the actual pepper heat. Safe."},

    // --- SPICES (SAFE & HEALING) ---
    {n:"Turmeric", s:"Friendly", c:"Seasonings", d:"Powerful anti-inflammatory. Great for bladder tissue health."},
    {n:"Salt / Sea Salt", s:"Friendly", c:"Seasonings", d:"The only seasoning that doesn't change urine pH. Very safe."},
    {n:"Himalayan Pink Salt", s:"Friendly", c:"Seasonings", d:"Safe; contains trace minerals to help buffer acidity."},
    {n:"Garlic Powder", s:"Friendly", c:"Seasonings", d:"Safer than raw garlic. Adds flavor without the 'bite'."},
    {n:"Onion Powder", s:"Avoid", c:"Seasonings", d:"Concentrated onion. Irritates prostate and bladder neck."},
    {n:"Ginger (Ground)", s:"Caution", c:"Seasonings", d:"Anti-inflammatory but 'sharp'. Test for stinging."},
    {n:"Black Pepper", s:"Caution", c:"Seasonings", d:"Known irritant; use sparingly during recovery."},
    {n:"Cinnamon / Nutmeg", s:"Caution", c:"Seasonings", d:"Fine in small amounts; can be a trigger if used heavily."},
    {n:"Paprika (Sweet)", s:"Caution", c:"Seasonings", d:"The only safe-ish pepper spice. Avoid 'Smoked' or 'Hot'."},
    {n:"Allspice / Cloves", s:"Caution", c:"Seasonings", d:"Warm spices can irritate the bladder neck in large doses."},
    {n:"Cardamom", s:"Caution", c:"Seasonings", d:"Generally safe, but has a strong 'perfume' profile for some."},
    {n:"Celery Seed", s:"Friendly", c:"Seasonings", d:"Safe and often used to reduce uric acid levels."},

    // --- PANTRY FLAVORINGS ---
    {n:"Vanilla Extract (Imitation)", s:"Caution", c:"Seasonings", d:"Better than pure extract as it often has less alcohol irritant."},
    {n:"Almond Extract", s:"Caution", c:"Seasonings", d:"Alcohol-based; can irritate the urethra if used heavily."},
    {n:"Baking Powder", s:"Caution", c:"Seasonings", d:"Contains cream of tartar (acid). Use in small amounts for baking."},
    {n:"Baking Soda", s:"Friendly", c:"Seasonings", d:"Strong alkalizer. Used to neutralize urine acid sting."},
    {n:"Cornstarch", s:"Friendly", c:"Seasonings", d:"Safe thickener for gravies and sauces."},
    {n:"Arrowroot Powder", s:"Friendly", c:"Seasonings", d:"Excellent safe alternative to cornstarch."},
    {n:"Coconut Aminos", s:"Caution", c:"Seasonings", d:"Safer than soy sauce, but still high in natural salt."},
    {n:"Carob Powder", s:"Friendly", c:"Seasonings", d:"The safe chocolate substitute. No caffeine."},

    // --- THE RED LIST (AVOID) ---
    {n:"Vinegar (White/Cider/Balsamic)", s:"Avoid", c:"Seasonings", d:"Pure acid. Primary trigger for mid-stream burning."},
    {n:"Soy Sauce / Tamari", s:"Avoid", c:"Seasonings", d:"Soy and high salt trigger nerve spasms. High flare risk."},
    {n:"MSG (Monosodium Glutamate)", s:"Avoid", c:"Seasonings", d:"Triggers nerve sensitivity and 'itchy' bladder feelings."},
    {n:"Ketchup / Mustard", s:"Avoid", c:"Seasonings", d:"Tomato/Vinegar-based. Major bladder irritants."},
    {n:"Hot Sauce / Chili Powder", s:"Avoid", c:"Seasonings", d:"Capsaicin burns the bladder neck during flow."},
    {n:"Red Pepper Flakes / Cayenne", s:"Avoid", c:"Seasonings", d:"Triggers intense sharp pain during urination."},
    {n:"Worcestershire Sauce", s:"Avoid", c:"Seasonings", d:"Vinegar and spice combo. High flare risk."},
    {n:"Artificial Sweeteners (Aspartame)", s:"Avoid", c:"Seasonings", d:"Chemical neurotoxins for the bladder lining."},
    {n:"Liquid Smoke", s:"Avoid", c:"Seasonings", d:"Chemical irritant. Triggers bladder spasms for many."},
    {n:"Tartar Sauce / Relish", s:"Avoid", c:"Seasonings", d:"Vinegar and preservatives are major triggers."},
    {n:"Bouillon Cubes (Standard)", s:"Avoid", c:"Seasonings", d:"High MSG, sodium, and onion/garlic powder triggers."},
    {n:"Meat Tenderizers", s:"Avoid", c:"Seasonings", d:"Often contain enzymes and MSG that irritate the bladder."}
];
