const data_vending = [
    // --- SALTY & CRUNCHY (THE "SAFE" CLUSTER) ---
    {n:"Lay's Classic Potato Chips", s:"Friendly", c:"Vending", d:"Pure potatoes, oil, salt. No citric acid or MSG."},
    {n:"Lay's Baked Original", s:"Friendly", c:"Vending", d:"Safe baseline. Avoid 'BBQ' or 'Sour Cream' baked versions."},
    {n:"Rold Gold Pretzels (Tiny Twists)", s:"Friendly", c:"Vending", d:"The safest staple in any machine. Non-acidic."},
    {n:"Snyder's Mini Pretzels", s:"Friendly", c:"Vending", d:"Safe and bland. Great for buffering stomach acid."},
    {n:"Snyder's Pretzel Rods", s:"Friendly", c:"Vending", d:"Safe. Thick pretzels are great for filling up without irritation."},
    {n:"Fritos Original Corn Chips", s:"Friendly", c:"Vending", d:"Safe. Only 3 ingredients. No hidden irritants."},
    {n:"Fritos Scoops", s:"Friendly", c:"Vending", d:"Safe baseline corn snack."},
    {n:"SunChips Original (Blue Bag)", s:"Friendly", c:"Vending", d:"Safe whole grains. Do NOT eat Harvest Cheddar or Salsa versions."},
    {n:"Popcorners Sea Salt", s:"Friendly", c:"Vending", d:"Clean corn snack. Very low irritant profile."},
    {n:"SkinnyPop Popcorn", s:"Friendly", c:"Vending", d:"Safe. Just popcorn, sunflower oil, and salt."},
    {n:"Smartfood White Cheddar", s:"Caution", c:"Vending", d:"Aged cheese can be an 'itch' trigger for some. Test small."},
    {n:"Stacy's Pita Chips (Sea Salt)", s:"Friendly", c:"Vending", d:"Very clean ingredients. No citric acid."},
    {n:"Chex Mix Traditional", s:"Caution", c:"Vending", d:"Contains onion/garlic powder. Can be a trigger in large amounts."},
    {n:"Gardetto's Original", s:"Avoid", c:"Vending", d:"Heavy onion, garlic, and spices. Major prostate irritant."},
    {n:"Munchies Snack Mix", s:"Avoid", c:"Vending", d:"Contains Doritos and Cheetos (Dyes/MSG). Absolute trigger."},

    // --- NUTS & SEEDS ---
    {n:"Planters Salted Peanuts", s:"Friendly", c:"Vending", d:"High protein and safe. Avoid 'Honey Roasted' (citric acid)."},
    {n:"Planters Cashews (Salted)", s:"Friendly", c:"Vending", d:"Non-acidic and very safe for the bladder."},
    {n:"Planters Trail Mix (Fruit & Nut)", s:"Avoid", c:"Vending", d:"The raisins/craisins in these are pure acid."},
    {n:"Planters Sunflower Kernels", s:"Friendly", c:"Vending", d:"Safe. Great for prostate and bladder health."},
    {n:"Wonderful Pistachios (Salted)", s:"Friendly", c:"Vending", d:"Safe baseline nut. Avoid 'Chili Roasted'."},
    {n:"Kar's Sweet 'n Salty Mix", s:"Avoid", c:"Vending", d:"Contains M&Ms (caffeine) and raisins (acid)."},
    {n:"CornNuts Original", s:"Friendly", c:"Vending", d:"Safe corn snack. Avoid 'Ranch' or 'Chile' flavors."},
    {n:"David Sunflower Seeds (Original)", s:"Friendly", c:"Vending", d:"Safe. Avoid 'BBQ' or 'Dill Pickle' versions."},

    // --- CRACKERS & COOKIES ---
    {n:"Kellogg’s Austin Peanut Butter Crackers", s:"Friendly", c:"Vending", d:"Safe bridge snack. Check for 'soy' if extremely sensitive."},
    {n:"Kellogg’s Austin Cheese/Peanut Butter", s:"Friendly", c:"Vending", d:"Generally safe. Non-acidic fillers."},
    {n:"Lance Toastchee (Peanut Butter)", s:"Friendly", c:"Vending", d:"Safe baseline cracker snack."},
    {n:"Lance Nekot (Vanilla/PB)", s:"Friendly", c:"Vending", d:"Safe sweet/salty option."},
    {n:"Rice Krispies Treats", s:"Friendly", c:"Vending", d:"The safest sweet choice. No caffeine, no acid."},
    {n:"Belvita Blueberry Biscuits", s:"Caution", c:"Vending", d:"Contains some citric acid; test in small amounts."},
    {n:"Belvita Golden Oat", s:"Friendly", c:"Vending", d:"Safest Belvita flavor. No fruit acid."},
    {n:"Nature Valley Oats 'n Honey", s:"Friendly", c:"Vending", d:"Safe granola bar. Avoid 'Fruit & Nut' or 'Dark Chocolate'."},
    {n:"Quaker Chewy Granola Bar (PB)", s:"Friendly", c:"Vending", d:"Safe. Avoid 'Chocolate Chip' or 'S'mores'."},
    {n:"Nabisco Nilla Wafers", s:"Friendly", c:"Vending", d:"Safe low-acid cookie. Good for buffering acid."},
    {n:"Nabisco Lorna Doone Shortbread", s:"Friendly", c:"Vending", d:"Safe. Simple flour, butter, sugar. No acid."},
    {n:"Nabisco Oreo Golden", s:"Caution", c:"Vending", d:"No chocolate, but high preservatives. Better than regular Oreos."},
    {n:"Nabisco Animal Crackers", s:"Friendly", c:"Vending", d:"Very safe and bland for flares."},
    {n:"Famous Amos Chocolate Chip", s:"Avoid", c:"Vending", d:"Caffeine in chocolate chips is a nerve irritant."},
    {n:"Grandma's Vanilla Creme Cookies", s:"Friendly", c:"Vending", d:"Safe alternative to chocolate cookies."},
    {n:"Grandma's Oatmeal Raisin", s:"Avoid", c:"Vending", d:"The raisins are concentrated tartaric acid. Trigger risk."},

    // --- CANDY ---
    {n:"PayDay Bar", s:"Friendly", c:"Vending", d:"The only safe 'Candy Bar'. Peanuts and caramel, NO chocolate."},
    {n:"Werther’s Original (Hard)", s:"Friendly", c:"Vending", d:"Safe caramel. Avoid 'Sugar Free' (Artificial sweeteners)."},
    {n:"Life Savers (Peppermint/Wint-O-Green)", s:"Friendly", c:"Vending", d:"Safe. Avoid the fruit-flavored Life Savers."},
    {n:"Mentos (Mint)", s:"Friendly", c:"Vending", d:"Safe. Avoid the fruit Mentos."},
    {n:"Andes Mints (White/Parfait)", s:"Friendly", c:"Vending", d:"Safe. Avoid the standard chocolate Andes."},
    {n:"Skittles / Starburst / Sour Patch", s:"Avoid", c:"Vending", d:"Pure citric/malic acid. 'Lemon on a cut' feeling guaranteed."},
    {n:"M&Ms / Snickers / Twix / Reese's", s:"Avoid", c:"Vending", d:"Caffeine/Theobromine in chocolate irritates bladder nerves."},
    {n:"Twizzlers / Red Licorice", s:"Avoid", c:"Vending", d:"Red Dye 40 and preservatives. Avoid while Botox settles."},

    // --- DRINKS ---
    {n:"Bottled Water (Aquafina/Dasani)", s:"Caution", c:"Vending", d:"Often acidic due to RO. Use your baking soda pinch."},
    {n:"SmartWater / Evian / Fiji", s:"Friendly", c:"Vending", d:"Naturally alkaline or pH balanced. Much safer."},
    {n:"Root Beer (Caffeine Free)", s:"Caution", c:"Vending", d:"Least bad soda. Bubbles can still sting during a flare."},
    {n:"Ginger Ale", s:"Caution", c:"Vending", d:"Contains citric acid, but better than dark colas."},
    {n:"Coke / Pepsi / Dr Pepper", s:"Avoid", c:"Vending", d:"High acid + Caffeine. Major flare trigger."},
    {n:"Mountain Dew", s:"Avoid", c:"Vending", d:"The 'Boss Level' of triggers: Caffeine, Yellow Dye, and Citric Acid."},
    {n:"Diet Sodas (All)", s:"Avoid", c:"Vending", d:"Artificial sweeteners are neurotoxins for the bladder."},
    {n:"Gatorade (All Colors)", s:"Avoid", c:"Vending", d:"Citric acid and dyes. The worst for bladder neck pain."},
    {n:"Dole Apple Juice", s:"Caution", c:"Vending", d:"Test small amounts. Some are very sharp/acidic."},
    {n:"Dole Orange Juice", s:"Avoid", c:"Vending", d:"Liquid fire for a sensitive bladder."}
];
